import { TCalculator } from './calculator.types';

export const CALCULATOR: TCalculator = {
  basic: [
    [
      {
        key: 'number_of_pages',
        title: 'Number of pages',
        mode: 'multiple',
        values: ['1 – 5', '5-15', '15-30', 'unlimited'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 200, 300, 1000],
      },
      {
        key: 'pages_copywrite',
        title: 'Pages Copywriting',
        mode: 'multiple',
        values: ['None', 'partly', 'all pages'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 100, 200],
      },
    ],
    [
      {
        key: 'styled_of_design',
        title: 'Style of design',
        mode: 'multiple',
        values: [
          'No design needed',
          'Simple yet attractive',
          'Moderately stylized',
          'high end',
          'world class',
        ],
        defaultIndex: 1,
        requiere: true,
        prices: [0, 100, 200, 300, 500],
      },
      {
        key: 'logo',
        title: 'Logo',
        mode: 'multiple',
        values: ['Not need', 'Basic logo', 'Modern logo'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
    ],
    [
      {
        key: 'db_integration',
        title: 'Database integration',
        mode: 'multiple',
        values: ['None', 'Basic', 'Advanced', 'Full development'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 100, 200, 300],
      },
      {
        key: 'form_email',
        title: 'Forms and emails',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'hard'],
        defaultIndex: 1,
        requiere: true,
        prices: [0, 100, 200],
      },
    ],
    [
      {
        key: 'e_commerece',
        title: 'E-Commerce',
        mode: 'multiple',
        values: ['Not need', '5-25 items', '25 – 100 Items', '100 + items'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 100, 200, 300],
      },
      {
        key: 'cms',
        title: 'CMS integration',
        mode: 'multiple',
        values: ['Not need', 'partly', 'fully'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 100, 200],
      },
      {
        key: 'seo',
        title: 'SEO',
        mode: 'simple',
        values: ['yes', 'no'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 0],
      },
    ],
  ],
  advanced: [
    [
      {
        key: 'number_of_pages',
        title: 'Number of pages',
        mode: 'multiple',
        values: ['1 – 5', '5 – 15', '15 -30', 'unlimited'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 200, 300, 500],
      },
      {
        key: 'copywrite',
        title: 'Pages Copywriting',
        mode: 'multiple',
        values: ['None', 'partly', 'all pages'],
        defaultIndex: 0,
        requiere: true,
        prices: [0, 200, 300],
      },
      {
        key: 'auth',
        title: ' Authorization / Registration',
        mode: 'multiple',
        values: ['Not need', 'basic', 'hard', 'web3'],
        defaultIndex: 0,
        requiere: true,
        prices: [0, 200, 300, 400],
      },
    ],
    [
      {
        key: 'styled_of_design',
        title: 'Style of design',
        mode: 'multiple',
        values: [
          'No design needed',
          'Simple yet attractive',
          'Moderately stylized',
          'high end',
          'world class',
        ],
        defaultIndex: 1,
        requiere: true,
        prices: [0, 100, 200, 300, 500],
      },
      {
        key: 'logo',
        title: 'Logo',
        mode: 'multiple',
        values: ['Not need', 'Basic logo', 'Modern logo'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'animation',
        title: 'Animation',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Modern', 'Extra hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500, 750],
      },
      {
        key: 'mobile_tablet',
        title: 'Mobile and tablet friendly design',
        mode: 'simple',
        values: ['yes', 'no'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 0],
      },
    ],
    [
      {
        key: 'db_integration',
        title: 'Database integration',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Advanced', 'Full development'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500, 750],
      },
      {
        key: 'livetime_actions',
        title: 'Live time actions => chat, notifications',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'day_scheduling',
        title: 'Day scheduling functionality',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'mail_sender',
        title: 'Email sender functionality',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
    ],
    [
      {
        key: 'e_commerece',
        title: 'E-Commerce',
        mode: 'multiple',
        values: ['Not need', '5-25 items', '25 – 100 Items', '100 + items'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 100, 200, 300],
      },
      {
        key: 'items_filtrations_categories',
        title: 'Items filtration and categories',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'checkout',
        title: 'Checkout',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
    ],
    [
      {
        key: 'forms_emails',
        title: 'Forms and emails',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'different_roles',
        title: 'Users with different roles',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'images',
        title: 'Images gallery',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'blog_reviews',
        title: 'Blog and Reviews',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'third_part',
        title: 'Third part services',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
    ],
    [
      {
        key: 'admin_panel',
        title: 'Custom admin panel',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'multy_lang',
        title: 'Multi language',
        mode: 'simple',
        values: ['yes', 'no'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 0],
      },
      {
        key: 'cms',
        title: 'CMS integration',
        mode: 'multiple',
        values: ['Not need', 'Basic', 'Hard'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
    ],
    [
      {
        key: 'seo',
        title: 'SEO',
        mode: 'simple',
        values: ['yes', 'no'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 0],
      },
      {
        key: 'metrica',
        title: 'Metrica',
        mode: 'simple',
        values: ['yes', 'no'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 0],
      },
      {
        key: 'webvisor',
        title: 'Webvisor',
        mode: 'simple',
        values: ['yes', 'no'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 0],
      },
    ],
    [
      {
        key: 'support',
        title: 'Support for app',
        mode: 'multiple',
        values: ['Not need', 'part of day', '24/7'],
        requiere: true,
        defaultIndex: 0,
        prices: [0, 250, 500],
      },
      {
        key: 'error_loger',
        title: 'Application errors logger',
        mode: 'simple',
        values: ['yes', 'no'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 0],
      },
      {
        key: 'protection',
        title: 'Protection against intruders ',
        mode: 'simple',
        values: ['yes', 'no'],
        defaultIndex: 0,
        requiere: true,
        prices: [100, 0],
      },
    ],
  ],
};
