export const List_In_Hive_DESIGN = [
  {
    title: 'listInHive.design.home.title',
    info: 'listInHive.design.home.subtitle',
    image: '/images/listInHive/listInHiveHome.png',
    reversed: false,
    with: 726,
    height: 638,
    class: 'designeInvesTonusPage1',
    mobImg: '/images/listInHive/listInHiveHomeMobile.png',
  },
  {
    title: 'listInHive.design.listing.title',
    info: 'listInHive.design.listing.subtitle',
    image: '/images/listInHive/listInHiveForms.png',
    reversed: true,
    with: 481,
    height: 617,
    class: 'designeInvesTonusPage2',
    mobImg: '/images/listInHive/listInHiveFormsMobile.png',
  },
  {
    title: 'listInHive.design.ai.title',
    info: 'listInHive.design.ai.subtitle',
    image: '/images/listInHive/listInHiveAi.png',
    reversed: false,
    with: 510,
    height: 290,
    class: 'designeInvesTonusPage3',
    mobImg: '/images/listInHive/listInHiveAiMobile.png',
  },
  {
    title: 'listInHive.design.ad.title',
    info: 'listInHive.design.ad.subtitle',
    image: '/images/listInHive/listInHiveAd.png',
    reversed: true,
    with: 336,
    height: 515,
    class: 'designeInvesTonusPage4',
    mobImg: '/images/listInHive/listInHiveAdMobile.png',
  },
  {
    title: 'listInHive.design.reviews.title',
    info: 'listInHive.design.reviews.subtitle',
    image: '/images/listInHive/listInHiveReviews.png',
    reversed: false,
    with: 620,
    height: 396,
    class: 'designeInvesTonusPage5',
    mobImg: '/images/listInHive/listInHiveReviewsMobile.png',
  },
];
